
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package jflex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LT = 11;
  public static final int ELSE = 4;
  public static final int NOTEQ = 9;
  public static final int RPAREN = 25;
  public static final int INT = 2;
  public static final int WHILE = 7;
  public static final int RETURN = 6;
  public static final int IF = 3;
  public static final int LPAREN = 26;
  public static final int GT = 10;
  public static final int ID = 27;
  public static final int NUM = 28;
  public static final int RSQBKT = 23;
  public static final int SUB = 19;
  public static final int RBRKT = 22;
  public static final int COMMA = 14;
  public static final int LTEQ = 13;
  public static final int EOF = 0;
  public static final int MULT = 16;
  public static final int SEMICOL = 18;
  public static final int DIV = 17;
  public static final int ADD = 15;
  public static final int LSQBKT = 24;
  public static final int error = 1;
  public static final int ASSIGN = 20;
  public static final int EQ = 8;
  public static final int GTEQ = 12;
  public static final int LBRKT = 21;
  public static final int VOID = 5;
  public static final int WHITESPACE = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "IF",
  "ELSE",
  "VOID",
  "RETURN",
  "WHILE",
  "EQ",
  "NOTEQ",
  "GT",
  "LT",
  "GTEQ",
  "LTEQ",
  "COMMA",
  "ADD",
  "MULT",
  "DIV",
  "SEMICOL",
  "SUB",
  "ASSIGN",
  "LBRKT",
  "RBRKT",
  "RSQBKT",
  "LSQBKT",
  "RPAREN",
  "LPAREN",
  "ID",
  "NUM",
  "WHITESPACE"
  };
}

