/* The following code was generated by JFlex 1.3.5 on 11/22/20, 10:39 PM */

package jflex;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;
import java.lang.*;
import java.io.InputStreamReader;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 11/22/20, 10:39 PM from the specification file
 * <tt>file:/F:/SaveProjectFiles/Eclipse/CMinus/lexer.jflex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner, sym {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\1\3\1\1\1\0\1\3\1\2\22\0\1\3\1\16\6\0"+
    "\1\37\1\40\1\5\1\12\1\20\1\11\1\0\1\4\12\10\1\0"+
    "\1\17\1\13\1\15\1\14\2\0\32\6\1\41\1\0\1\42\1\0"+
    "\1\7\1\0\3\6\1\27\1\30\1\22\1\6\1\34\1\21\2\6"+
    "\1\31\1\6\1\23\1\26\2\6\1\35\1\32\1\24\1\36\1\25"+
    "\1\33\3\6\1\43\1\0\1\44\uff82\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    37,    37,    74,   111,    37,   148,   185,    37,    37, 
      222,   259,   296,   333,    37,    37,   370,   407,   444,   481, 
      518,    37,    37,    37,    37,    37,    37,   555,    37,    37, 
       37,    37,   148,   592,   629,   666,   703,   740,   777,   148, 
      814,   851,   888,   925,    37,   148,   148,   962,   999,   148, 
     1036,   148
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\2\1\3\1\4\1\3\1\5\1\6\1\7\1\2"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\3\7\1\22\2\7\1\23\2\7\1\24"+
    "\1\7\1\25\1\7\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\46\0\1\3\50\0\1\34\45\0\3\7\10\0"+
    "\16\7\16\0\1\10\51\0\1\35\44\0\1\36\44\0"+
    "\1\37\44\0\1\40\35\0\3\7\10\0\1\7\1\41"+
    "\1\42\13\7\14\0\3\7\10\0\5\7\1\43\10\7"+
    "\14\0\3\7\10\0\10\7\1\44\5\7\14\0\3\7"+
    "\10\0\13\7\1\45\2\7\14\0\3\7\10\0\7\7"+
    "\1\46\6\7\6\0\5\34\1\47\37\34\6\0\3\7"+
    "\10\0\3\7\1\50\12\7\14\0\3\7\10\0\1\51"+
    "\15\7\14\0\3\7\10\0\11\7\1\52\4\7\14\0"+
    "\3\7\10\0\1\53\15\7\14\0\3\7\10\0\3\7"+
    "\1\54\12\7\6\0\4\34\1\55\1\47\37\34\6\0"+
    "\3\7\10\0\6\7\1\56\7\7\14\0\3\7\10\0"+
    "\7\7\1\57\6\7\14\0\3\7\10\0\10\7\1\60"+
    "\5\7\14\0\3\7\10\0\15\7\1\61\14\0\3\7"+
    "\10\0\7\7\1\62\6\7\14\0\3\7\10\0\14\7"+
    "\1\63\1\7\14\0\3\7\10\0\2\7\1\64\13\7"+
    "\6\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  9,  9,  1,  1,  9,  1,  1,  9,  9,  1,  1,  1,  1,  9,  9, 
     1,  1,  1,  1,  1,  9,  9,  9,  9,  9,  9,  0,  9,  9,  9,  9, 
     1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  9,  1,  1,  1, 
     1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
private String lastToken = " ";


/*
Check if two IDs, NUMs, and keywords are delimited with other token than IDs, NUMs, and keywords.
Otherwise return error with the "merged" ID.
*/
private boolean checkSeparator() {
   if(Character.isDigit(lastToken.charAt(lastToken.length() - 1))
      ||
      Character.isLetter(lastToken.charAt(lastToken.length() - 1))) {

      System.out.println("ERROR");
      error(lastToken + yytext());
      return false;
   }
   else {
      return true;
   }
}

public Lexer(ComplexSymbolFactory sf, java.io.InputStream is){
	this(is);
	symbolFactory = sf;
}

public Lexer(ComplexSymbolFactory sf, java.io.Reader reader){
	this(reader);
	symbolFactory = sf;
}

private StringBuffer sb;
private ComplexSymbolFactory symbolFactory;
private int csline, cscolumn;

public Symbol symbol(String name, int code) {
    return symbolFactory.newSymbol(name, code,
    				new Location(yyline + 1, yycolumn + 1, yychar),
    				new Location(yyline + 1, yycolumn + yylength(), yychar + yylength())
    				);
}

public Symbol symbol(String name, int code, Object lexem) {
    return symbolFactory.newSymbol(name, code,
    				new Location(yyline + 1, yycolumn + 1, yychar),
    				new Location(yyline + 1, yycolumn + yylength(), yychar + yylength()), lexem
    				);
}

private void error(String message) {
   System.out.println("Error at line "+ (yyline+1) + ", column " + (yycolumn+ 1)+ " : "+message);
}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[1073];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 112) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 30: 
          {  return symbol("EQ", EQ);  }
        case 53: break;
        case 8: 
          {  return symbol("SUB", SUB); }
        case 54: break;
        case 10: 
          {  return symbol("LT", LT);  }
        case 55: break;
        case 11: 
          {  return symbol("GT", GT);  }
        case 56: break;
        case 39: 
          { 
      if(checkSeparator()){

         return symbol("INT", INT);
      }
    }
        case 57: break;
        case 32: 
          { 
      if(checkSeparator()){

         return symbol("IF", IF);
      }
    }
        case 58: break;
        case 7: 
          { 
         if(checkSeparator()){

            return symbol("NUM", NUM, new Integer(Integer.parseInt(yytext())));
         }
       }
        case 59: break;
        case 51: 
          { 
      if(checkSeparator()){

         return symbol("RETURN", RETURN);
      }
    }
        case 60: break;
        case 6: 
        case 16: 
        case 17: 
        case 18: 
        case 19: 
        case 20: 
        case 33: 
        case 34: 
        case 35: 
        case 36: 
        case 37: 
        case 40: 
        case 41: 
        case 42: 
        case 43: 
        case 47: 
        case 48: 
        case 50: 
          { 
         if(checkSeparator()){

               return symbol("ID", ID, yytext());
         }
       }
        case 61: break;
        case 46: 
          { 
      if(checkSeparator()){

         return symbol("ELSE", ELSE);
      }
    }
        case 62: break;
        case 45: 
          { 
      if(checkSeparator()){

         return symbol("VOID", VOID);
      }
    }
        case 63: break;
        case 9: 
          {  return symbol("ADD", ADD);  }
        case 64: break;
        case 4: 
          {  return symbol("DIV", DIV);  }
        case 65: break;
        case 12: 
          {  return symbol("ASSIGN", ASSIGN);  }
        case 66: break;
        case 23: 
          {  return symbol("LSQBKT", LSQBKT);  }
        case 67: break;
        case 24: 
          {  return symbol("RSQBKT", RSQBKT);  }
        case 68: break;
        case 26: 
          {  return symbol("RBRKTS", RBRKT);  }
        case 69: break;
        case 1: 
        case 13: 
          {  System.out.println("ERROR");error(yytext()); }
        case 70: break;
        case 29: 
          {  return symbol("GTEQ", GTEQ);  }
        case 71: break;
        case 28: 
          {  return symbol("LTEQ", LTEQ);  }
        case 72: break;
        case 5: 
          {  return symbol("MULT", MULT);  }
        case 73: break;
        case 2: 
        case 3: 
          {  lastToken = " ";/* Ignore */  }
        case 74: break;
        case 21: 
          {  return symbol("LPAREN", LPAREN);  }
        case 75: break;
        case 22: 
          {  return symbol("RPAREN", RPAREN);  }
        case 76: break;
        case 49: 
          { 
      if(checkSeparator()){

         return symbol("WHILE", WHILE);
      }
    }
        case 77: break;
        case 44: 
          { /* Ignore */ }
        case 78: break;
        case 31: 
          {  return symbol("NOTEQ", NOTEQ);  }
        case 79: break;
        case 14: 
          {  return symbol("SEMICOL", SEMICOL);  }
        case 80: break;
        case 25: 
          {  return symbol("LBRKT", LBRKT);  }
        case 81: break;
        case 15: 
          {  return symbol("COMMA", COMMA);  }
        case 82: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
            switch (yy_lexical_state) {
            case YYINITIAL:
              {  return symbol("EOF", EOF);  }
            case 53: break;
            default:
              { return new java_cup.runtime.Symbol(sym.EOF); }
            }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
